In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
import sklearn
import os


In [2]:
#df1 = pd.read_json('Input URL link')
df = pd.read_csv('framingham.csv')
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
df_cleaned = df.dropna()
df_cleaned = df.drop("education", axis='columns')
df_cleaned.head()

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39              0         0.0     0.0                0   
1     0   46              0         0.0     0.0                0   
2     1   48              1        20.0     0.0                0   
3     0   61              1        30.0     0.0                0   
4     0   46              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [4]:
#Perform Binning
# def bin_age(age):
#     if age < 18:
#         return "Under 18"
#     elif age >= 18 and age < 25:
#         return "18-24"
#     elif age >= 25 and age < 35:
#         return "25-34"
#     elif age >= 35 and age < 45:
#         return "35-44"
#     elif age >= 45 and age < 55:
#         return "45-55"
#     else:
#         return "55 and older"

In [5]:
# df['Age Range'] = df['age'].apply(bin_age)
df_cleaned.describe()

male          age  currentSmoker   cigsPerDay       BPMeds  \
count  4238.000000  4238.000000    4238.000000  4209.000000  4185.000000   
mean      0.429212    49.584946       0.494101     9.003089     0.029630   
std       0.495022     8.572160       0.500024    11.920094     0.169584   
min       0.000000    32.000000       0.000000     0.000000     0.000000   
25%       0.000000    42.000000       0.000000     0.000000     0.000000   
50%       0.000000    49.000000       0.000000     0.000000     0.000000   
75%       1.000000    56.000000       1.000000    20.000000     0.000000   
max       1.000000    70.000000       1.000000    70.000000     1.000000   

       prevalentStroke  prevalentHyp     diabetes      totChol        sysBP  \
count      4238.000000   4238.000000  4238.000000  4188.000000  4238.000000   
mean          0.005899      0.310524     0.025720   236.721585   132.352407   
std           0.076587      0.462763     0.158316    44.590334    22.038097   
min           0.000000      0.000000     0.000000   107.000000    83.500000   
25%           0.000000      0.000000     0.000000   206.000000   117.000000   
50%           0.000000      0.000000     0.000000   234.000000   128.000000   
75%           0.000000      1.000000     0.000000   263.000000   144.000000   
max           1.000000      1.000000     1.000000   696.000000   295.000000   

             diaBP          BMI    heartRate      glucose   TenYearCHD  
count  4238.000000  4219.000000  4237.000000  3850.000000  4238.000000  
mean     82.893464    25.802008    75.878924    81.966753     0.151958  
std      11.910850     4.080111    12.026596    23.959998     0.359023  
min      48.000000    15.540000    44.000000    40.000000     0.000000  
25%      75.000000    23.070000    68.000000    71.000000     0.000000  
50%      82.000000    25.400000    75.000000    78.000000     0.000000  
75%      89.875000    28.040000    83.000000    87.000000     0.000000  
max     142.500000    56.800000   143.000000   394.000000     1.000000

In [6]:
#Perform Onehot Encoding
df_cleaned.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [7]:
df_cleaned = df_cleaned.dropna()
df_cleaned.shape

(3749, 15)

In [8]:
#Select Label and Feature from DataSets
y = df_cleaned[["TenYearCHD"]]
X = df_cleaned.drop("TenYearCHD", axis = 1)
X.head()

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39              0         0.0     0.0                0   
1     0   46              0         0.0     0.0                0   
2     1   48              1        20.0     0.0                0   
3     0   61              1        30.0     0.0                0   
4     0   46              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X) 
X[10,:]

array([-0.89576997,  0.04915618, -0.97705693, -0.75542723, -0.17709252,
       -0.07505363, -0.67312761, -0.16723694,  0.38218622,  0.02875575,
       -0.58111572, -0.71325938, -0.05887514, -0.24631379])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [11]:
#Create a Training model (examples)
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)
y_pred = LogReg.predict(X_test)
print(y_pred)

[0 0 0 ... 0 0 0]


c:\Users\trann\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
test_config_matrix = confusion_matrix(y_test, y_pred)
test_config_matrix

array([[945,   5],
       [164,  11]], dtype=int64)

In [13]:
test_accuracy_score = accuracy_score(y_test, y_pred)
test_accuracy_score

0.8497777777777777

In [14]:
test_class_report = classification_report(y_test, y_pred)
print(test_class_report)

              precision    recall  f1-score   support

           0       0.85      0.99      0.92       950
           1       0.69      0.06      0.12       175

    accuracy                           0.85      1125
   macro avg       0.77      0.53      0.52      1125
weighted avg       0.83      0.85      0.79      1125



In [15]:
train_prediction = LogReg.predict(X_train)
train_acc_score = accuracy_score(y_train, train_prediction)
train_acc_score

0.8551829268292683

In [16]:
print('Training set score: {:.4f}'.format(train_acc_score))

print('Test set score: {:.4f}'.format(test_accuracy_score))

Training set score: 0.8552
Test set score: 0.8498
